twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_5_layout.html.twig
        - form_div_layout.html.twig
        - utils/admin_form_div.html.twig
        - '@SpiriitFormFilter/Form/form_div_layout.html.twig'
    globals:
        project_version: '%env(PROJECT_VERSION)%'
    date:
        timezone: Europe/Paris
        format: d/m/Y

when@test:
    twig:
        strict_variables: true
